package nl.esciencecenter.eecology.classification.segmentloading;

import org.joda.time.DateTime;

/**
 * Represents the data from one annotated gps fix (row in table gps.uva_tracking_data101). This information can be generated by an
 * annotation tool.
 *
 * @author Christiaan Meijer, NLeSc
 *
 */
public class GpsRecordDto {
    private int deviceId;
    private DateTime timeStamp;
    private double longitude;
    private double latitude;
    private int altitude;
    private int pressure;
    private double temperature;
    private int satellitesUsed;
    private double gpsFixTime;
    private double positiondop;
    private double h_accuracy;
    private double v_accuracy;
    private double x_speed;
    private double y_speed;
    private double z_speed;
    private double speed_accuracy;
    private String location;
    private int userflag;
    private double speed2d;
    private double speed3d;
    private double direction;
    private double altitudeAboveGround;

    public void setTimeStamp(DateTime timeStamp) {
        this.timeStamp = timeStamp;
    }

    public DateTime getTimeStamp() {
        return timeStamp;
    }

    public void setDeviceId(int deviceId) {
        this.deviceId = deviceId;
    }

    public int getDeviceId() {
        return deviceId;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public int getAltitude() {
        return altitude;
    }

    public void setAltitude(int altitude) {
        this.altitude = altitude;
    }

    public int getPressure() {
        return pressure;
    }

    public void setPressure(int pressure) {
        this.pressure = pressure;
    }

    public double getTemperature() {
        return temperature;
    }

    public void setTemperature(double temperature) {
        this.temperature = temperature;
    }

    public int getSatellitesUsed() {
        return satellitesUsed;
    }

    public void setSatellitesUsed(int satellitesUsed) {
        this.satellitesUsed = satellitesUsed;
    }

    public double getGpsFixTime() {
        return gpsFixTime;
    }

    public void setGpsFixTime(double gpsFixTime) {
        this.gpsFixTime = gpsFixTime;
    }

    public double getPositiondop() {
        return positiondop;
    }

    public void setPositiondop(double positiondop) {
        this.positiondop = positiondop;
    }

    public double getH_accuracy() {
        return h_accuracy;
    }

    public void setH_accuracy(double h_accuracy) {
        this.h_accuracy = h_accuracy;
    }

    public double getV_accuracy() {
        return v_accuracy;
    }

    public void setV_accuracy(double v_accuracy) {
        this.v_accuracy = v_accuracy;
    }

    public double getX_speed() {
        return x_speed;
    }

    public void setX_speed(double x_speed) {
        this.x_speed = x_speed;
    }

    public double getY_speed() {
        return y_speed;
    }

    public void setY_speed(double y_speed) {
        this.y_speed = y_speed;
    }

    public double getZ_speed() {
        return z_speed;
    }

    public void setZ_speed(double z_speed) {
        this.z_speed = z_speed;
    }

    public double getSpeed_accuracy() {
        return speed_accuracy;
    }

    public void setSpeed_accuracy(double speed_accuracy) {
        this.speed_accuracy = speed_accuracy;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String geometry) {
        location = geometry;
    }

    public int getUserflag() {
        return userflag;
    }

    public void setUserflag(int userflag) {
        this.userflag = userflag;
    }

    public void setDirection(double direction) {
        this.direction = direction;
    }

    public double getDirection() {
        return direction;
    }

    public double getSpeed2d() {
        return speed2d;
    }

    public void setSpeed2d(double speed2d) {
        this.speed2d = speed2d;
    }

    public double getSpeed3d() {
        return speed3d;
    }

    public void setSpeed3d(double speed3d) {
        this.speed3d = speed3d;
    }

    public double getAltitudeAboveGround() {
        return altitudeAboveGround;
    }

    public void setAltitudeAboveGround(double altitudeAboveGround) {
        this.altitudeAboveGround = altitudeAboveGround;
    }

    /**
     * Sets the device id. This method exists so the csv reader can automatically find it based on the column headers of the csv
     * file.
     *
     * @param deviceId
     */
    public void setDevice_info_serial(int deviceId) {
        setDeviceId(deviceId);
    }

    /**
     * Sets the time stamp. This method exists so the csv reader can automatically find it based on the column headers of the csv
     * file.
     *
     * @param timeStamp
     */
    public void setDate_time(DateTime timeStamp) {
        setTimeStamp(timeStamp);
    }

    /**
     * Sets the satelites used. This method exists so the csv reader can automatically find it based on the column headers of the
     * csv file.
     *
     * @param satelites
     *            used
     */
    public void setSatellites_used(int satelites_used) {
        satellitesUsed = satelites_used;
    }

    /**
     * Sets the gps fix time used. This method exists so the csv reader can automatically find it based on the column headers of
     * the csv file.
     *
     * @param gps
     *            fix time
     */
    public void setGps_fixtime(double gps_fixtime) {
        gpsFixTime = gps_fixtime;
    }

    /**
     * Sets the speed parallel to the ground plane. This method exists so the csv reader can automatically find it based on the
     * column headers of the csv file.
     *
     * @param gps
     *            fix time
     */
    public void setSpeed_2d(double speed2d) {
        this.speed2d = speed2d;
    }

    /**
     * Sets the speed in 3d. This method exists so the csv reader can automatically find it based on the column headers of the csv
     * file.
     *
     * @param gps
     *            fix time
     */
    public void setSpeed_3d(double speed3d) {
        this.speed3d = speed3d;
    }

    /**
     * Sets the altitude above ground level. This method exists so the csv reader can automatically find it based on the column
     * headers of the csv file.
     *
     * @param gps
     *            fix time
     */
    public void setAltitude_agl(double altitudeAboveGround) {
        this.altitudeAboveGround = altitudeAboveGround;
    }
}
