package nl.esciencecenter.eecology.classification.segmentloading;

import org.joda.time.DateTime;

/**
 * Represents the data from one annotated gps fix. This information can be generated by an annotation tool.
 *
 * @author Christiaan Meijer, NLeSc
 *
 */
public class GpsRecordAnnotation {
    private int deviceId;
    private DateTime timeStamp;
    private int annotation;

    /**
     * Sets the device id. This method exists so the csv reader can automatically find it based on the column headers of the csv
     * file.
     *
     * @param deviceId
     */
    public void setDevice_info_serial(int deviceId) {
        setDeviceId(deviceId);
    }

    /**
     * Sets the time stamp. This method exists so the csv reader can automatically find it based on the column headers of the csv
     * file.
     *
     * @param timeStamp
     */
    public void setDate_time(DateTime timeStamp) {
        setTimeStamp(timeStamp);
    }

    /**
     * Sets the annotation. This method exists so the csv reader can automatically find it based on the column headers of the csv
     * file.
     *
     * @param annotation
     */
    public void setClass_id(int annotation) {
        setAnnotation(annotation);
    }

    public void setAnnotation(int annotation) {
        this.annotation = annotation;
    }

    public int getAnnotation() {
        return annotation;
    }

    public void setTimeStamp(DateTime timeStamp) {
        this.timeStamp = timeStamp;
    }

    public DateTime getTimeStamp() {
        return timeStamp;
    }

    public void setDeviceId(int deviceId) {
        this.deviceId = deviceId;
    }

    public int getDeviceId() {
        return deviceId;
    }
}
